### ISSUE TITLE
Apollo-server

### ISSUE THREAD

**Issue by rmeja** [TinisGames/crosswordGenerator#1]
I recommend using apollo-server instead of express-graphql. There are more useful features and the library is more up-to-date. Well, it's just a suggestion after all. Otherwise, how are you ? :wink:

**Comment by TineArconn** [comment]
Thanks for the advice. I'm going to watch this, I'm learning GraphQL, just to see ;)
I'm fine and you ?

**Comment by rmeja** [comment]
I'm good :muscle: :smile: 
This blog post from Marmelab was very useful for me to learn GraphQL : https://marmelab.com/blog/2017/09/06/dive-into-graphql-part-iii-building-a-graphql-server-with-nodejs.html.
Welcome to hell of ... I mean ... the paradise of resolvers in GraphQL :laughing:
